-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 21:43:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idfuncionario` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_quarto` (
  `idtipo_quarto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idtipo_quarto`),
  UNIQUE INDEX `idtipo_quarto_UNIQUE` (`idtipo_quarto` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quarto` (
  `idquarto` INT NOT NULL AUTO_INCREMENT,
  `num_quarto` INT NOT NULL,
  `tipo_quarto` INT NOT NULL,
  PRIMARY KEY (`idquarto`),
  UNIQUE INDEX `num_quarto_UNIQUE` (`num_quarto` ASC),
  UNIQUE INDEX `idquarto_UNIQUE` (`idquarto` ASC),
  INDEX `tipo_quarto_idx` (`tipo_quarto` ASC),
  UNIQUE INDEX `tipo_quarto_UNIQUE` (`tipo_quarto` ASC),
  CONSTRAINT `tipo_quarto`
    FOREIGN KEY (`tipo_quarto`)
    REFERENCES `mydb`.`tipo_quarto` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adm` (
  `idadm` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `idfunc` INT NOT NULL,
  PRIMARY KEY (`idadm`),
  INDEX `idfunc_idx` (`idfunc` ASC),
  UNIQUE INDEX `idfunc_UNIQUE` (`idfunc` ASC),
  CONSTRAINT `idfunc`
    FOREIGN KEY (`idfunc`)
    REFERENCES `mydb`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `fk_idcliente` INT NOT NULL,
  `fk_idfuncionario` INT NULL,
  `fk_idquarto` INT NOT NULL,
  `data_checkin` DATE NOT NULL,
  `data_checkout` DATE NOT NULL,
  `hora_checkin` TIME NOT NULL,
  `hora_checkout` TIME NOT NULL,
  PRIMARY KEY (`idreserva`),
  UNIQUE INDEX `idreserva_UNIQUE` (`idreserva` ASC),
  UNIQUE INDEX `idcliente_UNIQUE` (`fk_idcliente` ASC),
  UNIQUE INDEX `idquarto_UNIQUE` (`fk_idquarto` ASC),
  UNIQUE INDEX `idfuncionario_UNIQUE` (`fk_idfuncionario` ASC),
  CONSTRAINT `fk_idcliente`
    FOREIGN KEY (`fk_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idquarto`
    FOREIGN KEY (`fk_idquarto`)
    REFERENCES `mydb`.`quarto` (`idquarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idfuncionario`
    FOREIGN KEY (`fk_idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;