-- MySQL Script generated by MySQL Workbench
-- Wed May  3 21:16:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotelzin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelzin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelzin` DEFAULT CHARACTER SET utf8mb4 ;
USE `hotelzin` ;

-- -----------------------------------------------------
-- Table `hotelzin`.`adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelzin`.`adm` (
  `idadm` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto` MEDIUMBLOB NULL,
  PRIMARY KEY (`idadm`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotelzin`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelzin`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `foto` MEDIUMBLOB NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotelzin`.`tipo_quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelzin`.`tipo_quarto` (
  `idtipo_quarto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `preco` FLOAT NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_quarto`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotelzin`.`quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelzin`.`quarto` (
  `idquarto` INT(11) NOT NULL AUTO_INCREMENT,
  `num_quarto` INT(11) NOT NULL,
  `fk_tipo_quarto` INT(11) NOT NULL,
  PRIMARY KEY (`idquarto`),
  UNIQUE INDEX `num_quarto_UNIQUE` (`num_quarto` ASC) VISIBLE,
  INDEX `Quarto_TipoQuarto` USING BTREE (`fk_tipo_quarto`) VISIBLE,
  CONSTRAINT `Quarto_TipoQuarto`
    FOREIGN KEY (`fk_tipo_quarto`)
    REFERENCES `hotelzin`.`tipo_quarto` (`idtipo_quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotelzin`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelzin`.`reserva` (
  `idreserva` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_idcliente` INT(11) NOT NULL,
  `fk_idquarto` INT(11) NOT NULL,
  `data_checkin` DATE NULL DEFAULT NULL,
  `data_checkout` DATE NULL DEFAULT NULL,
  `hora_checkin` TIME NULL DEFAULT NULL,
  `hora_checkout` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `Fk_IdCliente` (`fk_idcliente` ASC) VISIBLE,
  INDEX `Fk_IdQuarto` (`fk_idquarto` ASC) VISIBLE,
  CONSTRAINT `Fk_IdCliente`
    FOREIGN KEY (`fk_idcliente`)
    REFERENCES `hotelzin`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_IdQuarto`
    FOREIGN KEY (`fk_idquarto`)
    REFERENCES `hotelzin`.`quarto` (`idquarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hotelzin`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelzin`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `foto` MEDIUMBLOB NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
